import React, { useState } from 'react';
import { X, FileText, Download } from 'lucide-react';
import { usePatients } from '../context/PatientContext';
import { useAuth } from '../context/AuthContext';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function ReportGeneratorModal({ isOpen, onClose }: ReportGeneratorModalProps) {
  const { patients } = usePatients();
  const { user } = useAuth();
  const [startMonth, setStartMonth] = useState('');
  const [endMonth, setEndMonth] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  if (!isOpen) return null;

  const handleGenerate = () => {
    if (!startMonth || !endMonth) return;

    setIsGenerating(true);
    setTimeout(() => {
      try {
        const [startYear, startM] = startMonth.split('-');
        const startDate = new Date(parseInt(startYear), parseInt(startM) - 1, 1);
        
        const [endYear, endM] = endMonth.split('-');
        const endDate = new Date(parseInt(endYear), parseInt(endM), 0, 23, 59, 59, 999);

        // Filter valid follow-ups
        let totalFollowUps = 0;
        let completed = 0;
        let missed = 0;
        let scheduled = 0;

        const allFollowUpsData: any[] = [];

        patients.forEach(patient => {
          if (patient.followUps && Array.isArray(patient.followUps)) {
            patient.followUps.forEach(f => {
              const followUpDate = new Date(f.date);
              if (followUpDate >= startDate && followUpDate <= endDate) {
                totalFollowUps++;
                if (f.status === 'Completed') completed++;
                else if (f.status === 'Missed') missed++;
                else scheduled++;

                allFollowUpsData.push([
                  patient.name,
                  patient.clinic || 'N/A',
                  new Date(f.date).toLocaleDateString(),
                  f.status,
                  f.officer || 'Unknown'
                ]);
              }
            });
          }
        });

        const doc = new jsPDF();
        
        // Header
        doc.setFontSize(20);
        doc.setTextColor(30, 58, 138); 
        doc.text('HOSPITAL TRACKING SYSTEM', 14, 22);
        
        doc.setFontSize(14);
        doc.setTextColor(51, 65, 85);
        doc.text('Patient Follow-up Statistics Report', 14, 32);

        doc.setFontSize(10);
        doc.text(`Generated By: ${user?.name || 'Admin'} (${user?.role})`, 14, 40);
        doc.text(`Period: ${startDate.toLocaleDateString('en-US', {month: 'long', year: 'numeric'})} to ${endDate.toLocaleDateString('en-US', {month: 'long', year: 'numeric'})}`, 14, 46);
        doc.text(`Generated On: ${new Date().toLocaleString()}`, 14, 52);

        // Summary Stats
        doc.setFillColor(241, 245, 249);
        doc.rect(14, 60, 182, 30, 'F');
        
        doc.setFontSize(12);
        doc.setTextColor(15, 23, 42);
        doc.text(`Total Follow-ups: ${totalFollowUps}`, 20, 70);
        doc.text(`Completed: ${completed}`, 20, 80);
        
        doc.text(`Missed: ${missed}`, 100, 70);
        doc.text(`Scheduled: ${scheduled}`, 100, 80);

        // Details Table
        doc.setFontSize(14);
        doc.text('Recent Follow-up Records', 14, 105);

        autoTable(doc, {
          startY: 110,
          head: [['Patient Name', 'Clinic', 'Date', 'Status', 'Officer']],
          body: allFollowUpsData.slice(0, 50), // Limit to 50 for summary if large
          theme: 'striped',
          headStyles: { fillColor: [37, 99, 235] },
          styles: { fontSize: 9 }
        });

        const exactDate = new Date().toISOString().split('T')[0];
        doc.save(`FollowUp_Report_${startMonth}_to_${endMonth}_${exactDate}.pdf`);
        onClose();
      } catch (error) {
        console.error("Error generating PDF:", error);
        alert("Failed to generate PDF. Check console for details.");
      } finally {
        setIsGenerating(false);
      }
    }, 500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
      <div className="bg-white rounded-3xl w-full max-w-md overflow-hidden shadow-2xl relative flex flex-col max-h-[90vh]">
        <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center">
              <FileText size={20} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Generate PDF Report</h3>
              <p className="text-xs text-slate-500">Summary of patient follow-ups</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-200 rounded-full transition-colors"
          >
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6 overflow-y-auto">
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Start Month</label>
              <input 
                type="month" 
                value={startMonth}
                onChange={(e) => setStartMonth(e.target.value)}
                className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">End Month</label>
              <input 
                type="month" 
                value={endMonth}
                onChange={(e) => setEndMonth(e.target.value)}
                className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none"
              />
            </div>
          </div>
        </div>
        
        <div className="p-6 border-t border-slate-100 bg-slate-50 shrink-0 flex justify-end gap-3">
          <button 
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-slate-600 hover:bg-slate-200 rounded-xl transition-colors"
          >
            Cancel
          </button>
          <button 
            onClick={handleGenerate}
            disabled={!startMonth || !endMonth || isGenerating}
            className="flex items-center gap-2 px-6 py-2 bg-blue-600 text-white text-sm font-bold rounded-xl hover:bg-blue-700 transition-colors disabled:opacity-50"
          >
            {isGenerating ? (
              <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <Download size={18} />
            )}
            Download PDF
          </button>
        </div>
      </div>
    </div>
  );
}
